json.id transaction.id
json.sender_id transaction.user_id
json.receiver_id transaction.receiver_id
json.sender_wallet_id transaction.sender_wallet_id
json.receiver_wallet_id transaction.receiver_wallet_id
json.amount transaction.amount
json.fee transaction.fee
json.exchange_rate transaction.exchange_rate
json.total_debit transaction.total_debit
json.created_at transaction.created_at
json.updated_at transaction.updated_at
